# Generated by Django 4.2.26 on 2025-11-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseriesentry",
            name="frequency",
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
