# Generated by Django 4.2.26 on 2025-11-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_timeseriesentry_frequency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpectrogramData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.FloatField()),
                ("values", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrogram_rows",
                        to="store.recordingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["frequency"],
                "unique_together": {("session", "frequency")},
            },
        ),
    ]
