# Generated by Django 4.2.26 on 2025-11-10 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_recordingsession_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordingsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesentry",
            name="timestamp",
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
