# Generated by Django 4.2.26 on 2025-11-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_recordingsession_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordingsession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="timeseriesentry",
            name="timestamp",
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
