# Generated by Django 4.2.26 on 2025-11-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_spectrogramdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRelatedPotential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latency", models.FloatField(blank=True, null=True)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=32, null=True)),
                ("values", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erps",
                        to="store.recordingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["latency", "channel"],
            },
        ),
    ]
