# Generated by Django 4.2.26 on 2025-11-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_recordingsession_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeseriesentry",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="timeseriesentry",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
