# Generated by Django 4.2.26 on 2025-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_eventrelatedpotential"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingsession",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
